### ISSUE TITLE
TBC backport

### ISSUE THREAD

**Issue by Macumbafeh** [shagu/ShaguError#1]
Hello.
I asked you already on your discord for the backport of this Addon for TBC. It was Just to remind you and add a written summary.

Btw, when you have Time. Thanks

**Comment by shagu** [comment]
Thanks for the reminder. It is now available for TBC :slightly_smiling_face: 

Related commits:
https://github.com/shagu/ShaguError/commit/d56e41a52820d6e60926f3a98e0868e3a2326966
https://github.com/shagu/ShaguError/commit/dde952b364162801aa12a2f04d9627617c28498a
https://github.com/shagu/ShaguError/commit/d221919db87beae2ce8e8f75b8834ef965fdc5ae
